# Generated by Django 4.1.2 on 2024-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
