# Generated by Django 4.1.2 on 2024-03-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='google_authenticator_secret_key',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
