# Generated by Django 4.1.2 on 2024-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usersetting_elo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='name',
            field=models.CharField(default='NoobMaster69', max_length=32),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='surname',
            field=models.CharField(default='NoobMaster69', max_length=32),
        ),
    ]
