# Generated by Django 4.1.2 on 2024-03-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_usersetting_google_authenticator_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='type_of_2fa',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
