# Generated by Django 4.1.2 on 2024-03-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_usersetting_name_usersetting_surname'),
        ('chat', '0004_alter_usersetting_google_authenticator_secret_key'),
    ]

    operations = [
    ]
