# Generated by Django 4.1.2 on 2024-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_match_usersetting_match_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='match_history',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
