# Generated by Django 4.1.2 on 2024-03-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_usersetting_type_of_2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='type_of_2fa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
