# Generated by Django 4.1.2 on 2024-02-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='friends',
            field=models.ManyToManyField(blank=True, to='chat.usersetting'),
        ),
    ]
