# Generated by Django 3.2.24 on 2024-02-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.URLField(default='https://i.ibb.co/cTHYRDn/OP73-K1g-Imgur.png'),
        ),
    ]
