# Generated by Django 3.2.24 on 2024-02-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240219_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
