# Generated by Django 3.2.24 on 2024-02-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_profile_pic'),
        ('api', '0004_customuser_last_request'),
    ]

    operations = [
    ]
