# Generated by Django 4.1.2 on 2024-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
