# Generated by Django 4.1.2 on 2024-05-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0003_alter_match_player2_alter_match_player3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
