# Generated by Django 4.1.2 on 2024-05-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trans_app', '0004_alter_match_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_scored', models.IntegerField(default=0)),
                ('points_conceded', models.IntegerField(default=0)),
                ('rallies', models.IntegerField(default=0)),
                ('time_played', models.IntegerField(default=0)),
                ('rallies_per_point', models.FloatField(default=0)),
                ('form', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('tournaments_won', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
