# Generated by Django 4.1.2 on 2024-05-06 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trans_app', '0007_remove_userstats_win_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player3_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player4_score',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='rallies_per_point',
        ),
        migrations.AddField(
            model_name='match',
            name='match_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('points_scored', models.IntegerField(default=0)),
                ('points_conceded', models.IntegerField(default=0)),
                ('rallies', models.IntegerField(default=0)),
                ('time_played', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans_app.match')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player1_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AddField(
            model_name='match',
            name='player3_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AddField(
            model_name='match',
            name='player4_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_stats', to='trans_app.usermatchstats'),
        ),
    ]
