# Generated by Django 4.1.2 on 2024-05-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0008_remove_match_player1_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatchstats',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='usermatchstats',
            name='match',
        ),
        migrations.RemoveField(
            model_name='usermatchstats',
            name='user',
        ),
        migrations.AddField(
            model_name='usermatchstats',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player3_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player3_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player4_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player4_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AlterField(
            model_name='usermatchstats',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
