# Generated by Django 4.1.2 on 2024-05-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0010_alter_userstats_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1_stats',
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player3_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_stats', to='trans_app.usermatchstats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player4_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_stats', to='trans_app.usermatchstats'),
        ),
    ]
