# Generated by Django 4.1.2 on 2024-05-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0011_remove_match_player1_stats_alter_match_player2_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_stats', to='trans_app.usermatchstats'),
        ),
    ]
