# Generated by Django 4.1.2 on 2024-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0012_match_player1_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='users',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='number_of_matches',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='wins',
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='name',
            field=models.CharField(default='NoobMaster69', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='surname',
            field=models.CharField(default='NoobMaster69', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='username',
            field=models.CharField(default='', max_length=3100),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
