# Generated by Django 4.1.2 on 2024-06-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0014_alter_usersetting_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(default='normal', max_length=100),
        ),
    ]
