# Generated by Django 4.1.2 on 2024-06-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_app', '0015_alter_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='isOuth',
            field=models.BooleanField(default=False),
        ),
    ]
